### ISSUE TITLE
Central location for transforms

### ISSUE THREAD

**Issue by matsumotosan** [Lightning-Universe/lightning-bolts#904]
Data transform classes for various models are included in their own folders in `pl_bolts/models`. It may be better to have them in `pl_bolts/transforms` instead.

Issue discussed with @otaj

**Comment by senarvi** [comment]
I was going to suggest the same thing. Also, at least SimCLR and MoCo can use the same transforms. Maybe we want to provide some transforms that can be used to replicate the paper results on some dataset, but do we want to provide a separate set of transforms for every model and every dataset?

**Comment by matsumotosan** [comment]
In general, I think the existing transforms are based on what the original papers specified (for whatever datasets they used). If a model by default uses transforms from another (i.e. BYOL using SimCLR transforms), I think we can just import SimCLRTransforms for BYOL instead of creating a copy and calling it BYOLTransforms. I think creating transforms for every model for every dataset might be too much though.

I'm all for standardizing how transforms are set up. I'm almost done moving everything over to `pl_bolts/transforms` so I'll let you know when I'm finished with that.

**Comment by otaj** [comment]
Hi, @matsumotosan, that would be great, thank you for kicking it off!

**Comment by matsumotosan** [comment]
All self-supervised transforms have been moved #905

**Comment by matsumotosan** [comment]
Commenting so this issue doesn't get closed.

All changes have been made in #905. Waiting for CI to be fixed so we can finish testing.
