### ISSUE TITLE
pytorch_lightning.loggers import LightningLoggerBase

### ISSUE THREAD

**Issue by zxkathy** [Lightning-Universe/lightning-bolts#972]
In data_monitor.py
```
pytorch_lightning.loggers import LightningLoggerBase
```
I always get the error message cannot import name 'LightningLoggerBase' from 'pytorch_lightning.loggers'

but would be working if 
```
from pytorch_lightning.loggers.base import LightningLoggerBase
```

Or if you update latest pytorch_lightning, they removed LightningLoggerBase completely, and use something else simpler.

**Comment by senarvi** [comment]
This is a duplicate of https://github.com/Lightning-AI/lightning-bolts/issues/962

**Comment by devdastl** [comment]
Is this issue solved? I can still see `LightningModule` in `data_monitor.py`

**Comment by tedtroxell** [comment]
@devdastl there's a PR that's been out for a little bit. I'm hoping that we can get it merged ASAP
